# Generated by Django 5.1.6 on 2025-04-21 04:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Kodi')),
                ('type', models.CharField(choices=[('SALE', 'Sotuv chegirmasi'), ('FREESHIP', 'Bepul yetkazish'), ('WELCOME', 'Yangi foydalanuvchi uchun'), ('BONUS', 'Bonus kupon')], default='SALE', max_length=20, verbose_name='Kupon turi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Soni')),
                ('used_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ishlatilgan soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Mahsulot surati', 'verbose_name_plural': 'Mahsulot suratlari'},
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('mg', 'Milligram'), ('l', 'Litr'), ('ml', 'Millilitr')], max_length=2, verbose_name="O'lchov birligi"),
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.coupons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi kuponi',
                'verbose_name_plural': 'Foydalanuvchi kuponlari',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
