# Generated by Django 5.1.6 on 2025-04-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_coupons_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='type',
        ),
        migrations.AddField(
            model_name='coupons',
            name='coupon_type',
            field=models.CharField(choices=[('SALE', 'Sotuv chegirmasi'), ('FREESHIP', 'Bepul yetkazish')], default='SALE', max_length=20, verbose_name='Kupon turi'),
        ),
    ]
